<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8a0673d221139f20566266af61f2900d
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Conexao' => __DIR__ . '/../..' . '/model/conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
        'Venda' => __DIR__ . '/../..' . '/model/Venda.class.php',
        'Vendedores' => __DIR__ . '/../..' . '/model/Vendedores.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8a0673d221139f20566266af61f2900d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8a0673d221139f20566266af61f2900d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8a0673d221139f20566266af61f2900d::$classMap;

        }, null, ClassLoader::class);
    }
}
