<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Conexao' => $baseDir . '/model/conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Rotas' => $baseDir . '/model/rotas.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'Venda' => $baseDir . '/model/Venda.class.php',
    'Vendedores' => $baseDir . '/model/Vendedores.class.php',
);
